package org.kie.example.project1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Role(org.kie.api.definition.type.Role.Type.EVENT)
public class RequestQualifier implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    private boolean critical;
    private java.lang.Long createdAt;
    private boolean processed;

    public RequestQualifier() {
    }

    public RequestQualifier(boolean critical, java.lang.Long createdAt,
                            boolean processed) {
        this.critical = critical;
        this.createdAt = createdAt;
        this.processed = processed;
    }

    public java.lang.Long getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(java.lang.Long createdAt) {
        this.createdAt = createdAt;
    }

    public boolean isProcessed() {
        return this.processed;
    }

    public void setProcessed(boolean processed) {
        this.processed = processed;
    }

    public boolean isCritical() {
        return this.critical;
    }

    public void setCritical(boolean critical) {
        this.critical = critical;
    }

    @Override
    public String toString() {
        return super.toString();
    }
}